--CREATE DATABASE taskDb

CREATE TABLE Task(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    [Description] VARCHAR(200) NOT NULL,
    Completed BIT DEFAULT(0) NOT NULL
    )
